### ISSUE TITLE
Query both top level tasks and subtasks using Live Query

### ISSUE THREAD

**Issue by OIDAM98** [silverbulletmd/silverbullet#589]
Taking the following list of tasks:
```markdown
- [ ] hello
- [ ] this is a task
- [ ] this is another task
  - [ ] with a subtask
  - [ ] complete this before test
    - [ ] test of a sub sub task
```

Right now, you can query all tasks that have at least a sub task with:
`#query task where nested != empty select name nested`
![Screenshot 2023-11-29 at 3 03 25 p m](https://github.com/silverbulletmd/silverbullet/assets/4955553/bcfbdf99-fac3-4317-8e89-f95eb59d4f70)

If you try to just query the tasks with no sub tasks by doing:
`#query task where nested = empty select name nested`
![Screenshot 2023-11-29 at 3 04 26 p m](https://github.com/silverbulletmd/silverbullet/assets/4955553/0436ec5e-fe15-4b0a-9d6d-39437b80162e)
You can see that sub tasks are also marked as top level tasks.

Also, two current bugs:
- for top level tasks that have sub tasks, Live Query return the sub tasks as part of the `name` and also the `nested` property.
- any task that has a sub task, breaks the default render strategy for Live Query, as shown here:
![Screenshot 2023-11-29 at 3 07 55 p m](https://github.com/silverbulletmd/silverbullet/assets/4955553/340586f7-6ef8-4b65-a597-8de13f84350f)

**Comment by devzero** [comment]
+1 for this feature -- maybe have the task objects point to a parent task if it is a subtask? and possibly indicate if all subtasks are marked off or not?  I'd find this very useful.
